
import React from 'react';
import { Difficulty } from '../types';

interface DifficultySelectorProps {
    onSelectDifficulty: (difficulty: Difficulty) => void;
}

export const DifficultySelector: React.FC<DifficultySelectorProps> = ({ onSelectDifficulty }) => {
    return (
        <div className="flex flex-col items-center justify-center min-h-screen bg-slate-900 text-white p-4">
            <div className="text-center mb-12">
                <h1 className="text-5xl font-bold mb-2">AI Sudoku</h1>
                <p className="text-slate-400">Puzzles generated by Gemini AI</p>
            </div>
            <div className="w-full max-w-xs space-y-4">
                <h2 className="text-2xl font-semibold text-center text-sky-400">Choose Difficulty</h2>
                {(Object.values(Difficulty) as Difficulty[]).map(level => (
                    <button
                        key={level}
                        onClick={() => onSelectDifficulty(level)}
                        className="w-full bg-slate-800 text-white text-lg font-bold py-4 px-6 rounded-xl border-2 border-slate-700 hover:bg-sky-600 hover:border-sky-500 transition-all duration-300 transform hover:scale-105 shadow-lg"
                    >
                        {level}
                    </button>
                ))}
            </div>
        </div>
    );
};
